<?php
$data = array (
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '辅食调味',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '31',
    'name' => '辅食调味',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '零食饮料',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => '零食饮料',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '电池',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '9',
    'name' => '电池',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '读卡器和内存卡',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '11',
    'name' => '读卡器和内存卡',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '充电器',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '7',
    'name' => '充电器',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '耳机',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '8',
    'name' => '耳机',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '辅食专区',
    'measure_unit' => '个',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '24',
    'name' => '辅食专区',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => 'Milupa 美乐宝',
    'measure_unit' => '个',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '26',
    'name' => 'Milupa 美乐宝',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '面条',
    'measure_unit' => '个',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '29',
    'name' => '面条',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '糖果',
    'measure_unit' => '个',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '28',
    'name' => '糖果',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => 'Hipp 喜宝',
    'measure_unit' => '个',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '25',
    'name' => 'Hipp 喜宝',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '生活用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '32',
    'name' => '生活用品',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '蔬菜水果',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '蔬菜水果',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '双模手机',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 5,
    'level' => 1,
    'id' => '5',
    'name' => '双模手机',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => 'CDMA手机',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 2,
    'level' => 1,
    'id' => '2',
    'name' => 'CDMA手机',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => 'GSM手机',
    'measure_unit' => '台',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 14,
    'level' => 1,
    'id' => '3',
    'name' => 'GSM手机',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '3G手机',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '4',
    'name' => '3G手机',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '宝宝奶粉区',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '16',
    'name' => '宝宝奶粉区',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '宝宝腹泻奶粉',
    'measure_unit' => '个',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '23',
    'name' => '宝宝腹泻奶粉',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '德国Holle鸿乐/凯莉',
    'measure_unit' => '个',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '20',
    'name' => '德国Holle鸿乐/凯莉',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '德国Aptamil爱他美',
    'measure_unit' => '个',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '18',
    'name' => '德国Aptamil爱他美',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '德国Bambinchen羊奶',
    'measure_unit' => '个',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '21',
    'name' => '德国Bambinchen羊奶',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '德国Nestle雀巢BEBA',
    'measure_unit' => '个',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '19',
    'name' => '德国Nestle雀巢BEBA',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '德国成人奶粉',
    'measure_unit' => '个',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '22',
    'name' => '德国成人奶粉',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '德国Hipp 喜宝',
    'measure_unit' => '个',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '17',
    'name' => '德国Hipp 喜宝',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '速冻食品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '30',
    'name' => '速冻食品',
  ),
);
?>